import json

with open("config.json","r") as config_file:
        config_data = json.load(config_file)
    
MONSTERS_LIST = config_data["MONSTERS_LIST"]
AVATAR_LIST = config_data["AVATAR_LIST"]
PICK_UP_LIST = config_data["PICK_UP_LIST"]

MILESTONES_FOR_PICK_UP = config_data["PICK_UP_DATA"]["MILESTONES_FOR_PICK_UP"]
MILESTONES_FOR_PICK_UP_LIST = list(MILESTONES_FOR_PICK_UP.values())

TOTAL_NO_OF_STEPS_TILL_FINISH = config_data["TOTAL_NO_OF_STEPS_TILL_FINISH"]

TOTAL_NO_OF_PICK_UPS = config_data["PICK_UP_DATA"]["TOTAL_NO_OF_PICK_UPS"]

ATTACK_RESULTS = config_data["ATTACK_RESULTS"]

ESCAPE_RESULTS = config_data["ESCAPE_RESULTS"]

MIN_STEPS_WHILE_ROLLING_DICE = config_data["STEP_LIMITS_ON_DICE_ROLL"]["MIN_STEPS_WHILE_ROLLING_DICE"]
MAX_STEPS_WHILE_ROLLING_DICE = config_data["STEP_LIMITS_ON_DICE_ROLL"]["MAX_STEPS_WHILE_ROLLING_DICE"]

NO_OF_MONSTERS_TO_BE_KILLED_MAX_FOR_LEVEL_ONE = config_data["MONSTERS_KILLED_LIMITS_FOR_DIFFERENT_LEVELS"]["NO_OF_MONSTERS_TO_BE_KILLED_MAX_FOR_LEVEL_ONE"]
NO_OF_MONSTERS_TO_BE_KILLED_MAX_FOR_LEVEL_TWO = config_data["MONSTERS_KILLED_LIMITS_FOR_DIFFERENT_LEVELS"]["NO_OF_MONSTERS_TO_BE_KILLED_MAX_FOR_LEVEL_TWO"]
NO_OF_MONSTERS_TO_BE_KILLED_MIN_FOR_LEVEL_THREE = config_data["MONSTERS_KILLED_LIMITS_FOR_DIFFERENT_LEVELS"]["NO_OF_MONSTERS_TO_BE_KILLED_MIN_FOR_LEVEL_THREE"]
    